In [ ]:
import numpy as np

In [ ]:
#np.array([list], dtype='int')
score = np.loadtxt('survey.txt',dtype='int')

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
len(score)

1167

In [ ]:
#Starting Five values
score[:5]

array([ 7, 10,  5,  9,  9])

In [ ]:
type(score)

numpy.ndarray

In [ ]:
#Math Function
score.min()

1

In [ ]:
score.max()

10

In [ ]:
score <= 6

array([False, False,  True, ...,  True, False, False])

In [ ]:
score[score<=6]

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [ ]:
defractor = score[score<=6]

In [ ]:
len(defractor)

332

In [ ]:
promoter = score[score >= 9]

In [ ]:
len(promoter)

609

In [ ]:
total = len(score)

In [ ]:
perc_promoters = (len(promoter)/total) * 100

In [ ]:
perc_defractors = (len(defractor)/total) * 100

In [ ]:
NPS = perc_promoters - perc_defractors

In [ ]:
NPS

23.73607540702657